#define BLYNK_TEMPLATE_ID "TMPL6MS6btZfW"
#define BLYNK_TEMPLATE_NAME "Temp SoilM EC"
#define BLYNK_AUTH_TOKEN "f5XIvNr_EdZSWJidGU7163s3LOgIwvnz"
// #define WIFI_SSID "dinfo"
// #define WIFI_PASS "daon7521"